import streamlit as st

# Basic Information
st.title("Your Name")
st.subheader("Job Title or Field")
st.write("Location | Contact: email@example.com | LinkedIn: [your-linkedin-profile](https://linkedin.com)")

# Summary
st.header("Summary")
st.write("""
Experienced [Job Title] with a demonstrated history of working in the [Industry]. Skilled in [Skill1, Skill2, Skill3]. 
Passionate about leveraging data and technology to drive impactful solutions.
""")

# Skills
st.header("Skills")
skills = ["Python", "Machine Learning", "Data Analysis", "Project Management", "Communication"]
st.write(", ".join(skills))

# Experience Section
st.header("Experience")
st.subheader("Job Title 1 | Company Name")
st.write("**Dates Employed**: Month Year - Month Year")
st.write("""
- Responsibility 1: Achieved X results through Y methodology.
- Responsibility 2: Improved efficiency by Z%.
""")

st.subheader("Job Title 2 | Previous Company")
st.write("**Dates Employed**: Month Year - Month Year")
st.write("""
- Key responsibility and accomplishments.
- Achievements and contributions.
""")

# Education
st.header("Education")
st.subheader("Degree, Major | University Name")
st.write("**Graduation Year**: YYYY")
st.write("Relevant coursework, projects, honors, or awards.")

# Projects
st.header("Projects")
st.subheader("Project Title")
st.write("""
- Brief description of the project.
- Skills demonstrated: Skill1, Skill2.
- [Link to project or repository](https://github.com/your-github)
""")

# Certifications (Optional)
st.header("Certifications")
st.write("""
- Certification Name, Issuing Organization, Year
- Certification Name, Issuing Organization, Year
""")

# Footer
st.write("---")
st.write("Generated by [Streamlit](https://streamlit.io/)")

